# Usa una imagen base adecuada para tu frontend (por ejemplo, Node.js)
FROM node:latest as build-stage

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (o el equivalente) para instalar dependencias
COPY package.json .
COPY package-lock.json .

# Instala las dependencias del frontend
RUN npm install

COPY . .

RUN npm run build

# Segunda etapa para servir los archivos estáticos
FROM nginx:alpine

# Copia los archivos estáticos del frontend compilado desde la etapa de compilación
COPY --from=build-stage ./app/dist/ /usr/share/nginx/html

COPY nginx.config /etc/nginx/nginx.conf

# Exponer el puerto 80 para que Nginx pueda servir la aplicación
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

