# Usa una imagen base adecuada para tu frontend (por ejemplo, Node.js)
FROM node:latest as build-stage

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (o el equivalente) para instalar dependencias
COPY ./package*.json ./

# Instala las dependencias del frontend
RUN npm install

# Copia el resto de los archivos del frontend al directorio de trabajo
COPY ./ ./

# Compila o construye tu frontend
RUN npm run build

# Segunda etapa para servir los archivos estáticos
FROM nginx:latest

# Copia los archivos estáticos del frontend compilado desde la etapa de compilación
COPY --from=build-stage ./app/dist/ /usr/share/nginx/html

# Exponer el puerto 80 para que Nginx pueda servir la aplicación
EXPOSE 80

# Nginx ya está configurado por defecto para iniciar el servidor web
