version: '3'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network

  backend:
    image: erazoex/backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"  
    depends_on:
      - mysql-container
    networks:
      - my-network

  frontend:
    image: erazoex/frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"  
    depends_on:
      - backend
    networks:
      - my-network
    
networks:
  my-network:
    driver: bridge