# Usa la imagen base de Nginx
FROM nginx:latest

# Elimina la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia tu archivo de configuración personalizado de Nginx al contenedor
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para que el contenedor sea accesible desde fuera
EXPOSE 80

# docker build -t nginx-image ./nginx-config
